server:
  port: 7923
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: ${local.config.spring.name}
  profiles:
    active: dev

knife4j:
  enable: true
  setting:
    language: zh-CN
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Apache License 2.0 | Copyright  2021-[${author}](https://wiki.hicoofinal.com/spaces/viewspace.action?key=~${author})
  production: false

logging:
  level:
    root: info
  pattern:
    console: '%red(%d{yyyy-MM-dd HH:mm:ss.SSS}) %red([${spring.application.name}]) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger) - %cyan(%msg%n)'